// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class TC01NaysearchbluetothheadphoneverifyTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void tC01Naysearchbluetothheadphoneverify() {
    driver.get("https://www.nay.sk");
    driver.manage().window().setSize(new Dimension(1920, 1080));
    driver.findElement(By.xpath("//input[@placeholder=\"Zadajte text pre vyhľadávanie\"]")).sendKeys("slúchadlá");
    driver.findElement(By.xpath("//div[@id=\"header\"]/div[1]/div[1]/div[2]/form/div[2]/div[2]/div/div/div[2]/div/div[1]/ul/li[1]/a/span")).click();
    assertThat(driver.findElement(By.xpath("//div[@id=\"__layout\"]/div/div[3]/div[3]/section[1]/div[1]/h1")).getText(), is("BLUETOOTH SLÚCHADLÁ "));
  }
}
